{
    "HI":{"PT":"oi","EN":"hi","ES":"ola","FR":"salut"},
    "SLOGAN":{"PT":"fotografia","EN":"photography","ES":"fotografia","FR":"photographie"},
    "PORTFOLIO":{"PT":"portifólio","EN":"portfolio","ES":"portafolio","FR":"portefeuille"},
    "GALLERY":{"PT":"galeria","EN":"gallery","ES":"galería","FR":"galerie"},
    "COLLECTION":{"PT":"coleção","EN":"collection","ES":"colección","FR":"collection"},
    "SPECTACLE":{"PT":"espetáculo","EN":"presentation","ES":"espectáculo","FR":"spectacle"},
    "PT":{"PT":"português","EN":"portuguese","ES":"portugués","FR":"portugais"},
    "FR":{"PT":"frances","EN":"french","ES":"francés","FR":"français"},
    "EN":{"PT":"inglês","EN":"english","ES":"inglés","FR":"anglais"},
    "ES":{"PT":"espanhol","EN":"spanish","ES":"español","FR":"espagnol"},
    "LIBRARY":{"PT":"biblioteca","EN":"library","ES":"biblioteca","FR":"bibliothèque"},
    "AUTHOR":{"PT":"autor","EN":"author","ES":"autor","FR":"auteur"},
    "CONTACT":{"PT":"contato","EN":"contact","ES":"contato","FR":"contato"},
    "ABOUT":{"PT":"sobre","EN":"about","ES":"sobre","FR":"sur"},
    "SHARE":"share",
    "LANGUAGE":{"PT":"linguagem","EN":"language","ES":"idioma","FR":"langue"},
    "SOCIAL":"social",
    "BIO":"bio",
    "FEED":"feed",
    "NOTES":{"PT":"notas","EN":"notes","ES":"notas","FR":"notes"},
    "COPYRIGHT":"copyright",
    "CLIPPING":"clipping",
    "PUB":"pub",
    "GOODMORNING" : {"PT" : "bom dia","ES" : "buenos días","EN" : "good mornig","FR" : "bonjour"},
    "GOODNIGHT" : {"PT" : "boa noite","ES" : "buenos noches","EN" : "good night","FR" : "bonsoir"},
    "LOGIN_TITLE":{"PT":"identificação","EN":"identification","ES":"identificación","FR":"identification"},
    "MAIL":"email",
    "USER_ID":{"PT":"usuário","EN":"user","ES":"usuario","FR":"utilisateur"},
    "USER_PASS":{"PT":"senha","EN":"password","ES":"contraseña","FR":"mot de passe"},
    "BUTTON_REGISTER":{"PT":"cadastrar","EN":"register","ES":"registrarse","FR":"enregistrer"},
    "BUTTON_LOGIN":{"PT":"identificar-se","EN":"login","ES":"entrar","FR":"s'identifier"},
    "BUTTON_LOGOUT":{"PT":"sair","EN":"logout","ES":"sair","FR":"déconnexion"},
    "BUTTON_REMEMBER":{"PT":"esqueci minha senha","EN":"forgot password","ES":"no recuerdo de ma contraseña","FR":"mot de passe oublié"},
    "DOWNLOADWEB_BUTTON_TIP":{"PT":"baixar foto em resolução web","EN":"download picture in web resolution","FR":"télécharger la photo en résolution moyenne"},
    "PERMALINK_BUTTON_TIP": {"PT":"link permanente para imagem","EN":"permanent link to image","FR":"lien permanent vers l'image"},
    "MAIL_BUTTON_TIP": {"PT":"enviar imagem por email","EN":"send image by mail","FR":"envoyer l'image par mail"},
    "FACEBOOK_BUTTON_TIP": {"PT":"compartilhar imagem no facebook","EN":"share image on facebook","FR":"partager l'image sur facebook"},
    "PINTEREST_BUTTON_TIP": {"PT":"compartilhar imagem no pinterest","EN":"share image on pinterest","FR":"partager l'image sur pinterest"},
    "GPLUS_BUTTON_TIP": {"PT":"compartilhar imagem no google plus","EN":"share image on google plus","FR":"partager l'image sur google plus"},
    "TWITTER_BUTTON_TIP": {"PT":"compartilhar imagem no twitter","EN":"share image on twitter","FR":"partager l'image sur twitter"}
}